default_stages: [pre-commit, pre-push]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-toml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: tests/mock_confluence\.py

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.11
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
        files: \.(json|md|yaml|yml)$

  - repo: local
    hooks:
      - id: revert-changelog-rc
        name: revert changelog rc headings
        entry: uv run scripts/revert_changelog_rc.py
        language: system
        files: CHANGELOG.md
        stages: [pre-commit]
      - id: tox
        name: tox
        entry: uv run tox -e py312
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-push]
